site_name: koor
site_description: KOOR is a project that aims to connect employers, job seekers, and vendors in a single platform.
repo_url: https://github.com/digimonkt/koor-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/digimonkt">digimonkt</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
