name: koor

on:
  push:
    branches: [ "main" ]

jobs:
  python-koor_backend:

    runs-on: ubuntu-latest

    steps:
 
    - name: Checkout

      uses: actions/checkout@v3

    - name: Deployment

      uses: appleboy/ssh-action@master

      with:

        host: 203.190.153.20

        key: ${{ secrets.SSH_PRIVATE_KEY }}

        username: user
        
        port: 22

        script: |
          cd /home/user/koor/backend_koor/ 
          git pull origin main
